brianvoe/gofakeit

address.go

Before: ![Before](http://i.imgur.com/SayCcAg.png)
After: ![After](http://i.imgur.com/N53MWWm.png)

Fixes extra space between street name and suffix

---

misc.go
misc_test.go

`replaceWithNumbers` panics if the argument is an
empty string.
This case was triggered when Generate() is
called with "{person.invalid}" argument.
This results in an empty string as an argument
to `replaceWithNumbers`.

fix: handle an edge case to avoid panic

---

internet.go

To keep compat with go < 1.12, this PR uses `strings.Replace(..., -1)` instead of `strings.ReplaceAll()`.

strings.Replace(..., -1) instead of strings.ReplaceAll() for go<1.12

---

payment.go
payment_test.go

Apparently the regex I posted in https://github.com/brianvoe/gofakeit/issues/116 was flawed, It actually should be `^5[HJK][1-9A-Za-z][^OIl]{49}$`
This small commit makes output compliant with correct regex

payment - fix bitcoin private key structure

---

hacker.go

When I tried to generate some random sentences with `HackerPhrase()`, I found something strange:
```
You can't calculate the alarm without quantifying the bluetooth JBOD protocol!
I'Ll connect the digital JBOD card, that should synthesize the SAS array!
You can't synthesize the system without copying the mobile RSS matrix!
We need to bypass the neural AGP monitor!
I'Ll hack the mobile SAS panel, that should parse the TCP bus!
Navigating the sensor won't do anything, we need to back up the haptic JBOD system!
```
Some of the sentences start with `I'Ll` seems incorrect.
It looks like the first `l` of `'ll` was mapped to uppercase unexpectedly, and I believe it should be `I'll`.
The template of this sentence is located here:
https://github.com/brianvoe/gofakeit/blob/0418e53a6281759a8723e4e84e …

fix "I'll" mapped to "I'Ll" when it's the first word

---

README.md

While updating one of my projects from v3 to v6, I noticed that `SimpleStatusCode` was renamed, but the readme still showed the old one.
I have now gone through all categories mentioned in the readme and verified all function names and arguments.
I have also added some missing ones and made the naming of the headings more consistent (some were singular, some were plural).

Readme - update function definitions

---

.github/workflows/go.yml
README.md
data/internet.go
internet.go
internet_test.go

- This PR Adds HTTP version to the list of fakers.
- Add go lang 1.16 to the github workflow list (Can travis.yml be removed?)

Add HTTPVersion to the list of fakers

---

cmd/gofakeit/README.md
cmd/gofakeitserver/README.md

Current installation instruction for gofakeit cli and gofakeit server is incorrect. This PR fixes it

Fix installation instruction for gofakeit cli and gofakeit server

---

struct.go
struct_test.go

Re-filling struct's empty slice field leads to panic. pr addresses the issue.
```go
func TestStructSliceLoopGeneration(t *testing.T) {
type S struct {
A []string
}
s := &S{}
for i := 0; i < 2; i++ {
if err := Struct(s); err != nil {
t.Fatal(err)
}
}
}
```
```
✗ go test -v -run="^TestStructSliceLoopGeneration$"
panic: reflect: slice index out of range [recovered]
panic: reflect: slice index out of range
goroutine 6 [running]:
testing.tRunner.func1.2(0x6207a0, 0x6dd420)
/usr/local/go/src/testing/testing.go:1144 +0x332
testing.tRunner.func1(0xc000001680)
/usr/local/go/src/testing/testing.go:1147 +0x4b6
panic(0x6207a0, 0x6dd420)
/usr/local/go/src/runtime/panic.go:965 +0x1b9
reflect.Value.Index(0x61e760, 0xc00000c0d8, 0x197, 0x9, 0xc000056b90, 0x198, 0x0)
/usr/local/go/src/reflect/value.go:962 …
```

Fix slice field loop generation.

---

internet_test.go
struct.go
struct_test.go

A custom function for a type that is internally a slice/array is now
used instead of populating the array with random members.
Refs: #202

Fix custom function for net.IP

---

cmd/gofakeit/README.md

Starting in Go 1.17, installing executables with go get is deprecated. go install is the recommended way of installing executables - https://go.dev/doc/go-get-install-deprecation
This merge request adds command that uses go install to install gofakeit cli as a command and works across Go versions.

Replacing go get with go install in README.md

---

README.md
struct.go
struct_test.go

This PR adds a range to the `fakesize` struct tag, allowing it to accept both a single number, as well as a comma separated min and max value:
```
type User struct {
Id         int      `fake:"{number}"`
Username   string   `fake:"{username}"`
Notes      []string `fakesize:"8" fake:"{sentences}"`
Attributes []string `fakesize:"2,4" fake:"{word}"`
}
```
This implementation feels like it fits with the code style in the rest of the repo, but please let me know if there's anything you'd like changed, or anything I've missed!

Allow fakesize to accept a range of numbers

---

csv.go
json.go
json_test.go
lookup.go
struct.go
xml.go

There are two types in `encoding/json` that are special:
- `json.RawMessage` is defined as a `[]byte` and it is used to store unparsed JSON. When encountered in a struct, gofakeit generates a random array of bytes but that doesn't mean that it is a valid JSON, and it will fail when trying to `json.Marshal` the struct.
- `json.Number` is defined as a `string` and it is used to represent numeric types in JSON. When encountered in a struct, gofakeit generates a random string that cannot be represented as a number and it will fail when trying to `json.Marshal` the struct.
This PR adds support for those two types in the `encoding/json` package ensuring that valid JSON values are generated by gofakeit by default and that the resulting struct can be marshalled to JSON. More precise output …

Safe json.RawMessage and json.Number

---

struct.go

add the tag name to the error message to make live easier when searching for a not implemented function.
fix some typos.

Indicate in error msg which function is not found

---

address.go
address_test.go
faker_test.go
generate_test.go
json_test.go
person_test.go

Fixes #252 
It looks like historically StreetSuffix has always been used to internally generate random sounding street names, where as one would want a StreetSuffix generator to be true street name suffixes we encounter in real life: 
```
[
Boulevard,
Place,
Road,
Way,
Terrace,
Court,
Lane,
Circle,
Trail,
Avenue,
Drive,
Street
]
```
Perhaps the current StreetSuffix function should be an internal function and the public one generate names from the corresponding list.

Reverts 8ac39ba

---

struct.go
struct_test.go

Tiny addition to avoid errors with libraries that automatically adds tags like json to be skipped with `-`.
In my case, it's an orm generator, to which when I introduced gofakeit and fake tag, it automatically added `fake:"-"` which broke faker.
I managed to manually get fixed changing fake:"-" to fake:"skip".
Amazing library, thanks @brianvoe for all the efforts into it.

feat(struct): interpret dash (`-`) as skip

---

generate_test.go
number.go

This PR will allow to use randomint & randomuint in struct tags.
As for now, it's not possible and leads to the following error:
```go
strconv.ParseUint: parsing "{randomuint:[1,2,3]}": invalid syntax
```

Add randomint & randomuint func lookup

---

struct.go
struct_test.go

When a map type field is defined in a structure, its `t.Name()` will return an empty string and the `fake` tag will be invalid. 
Remove `t.Name()!=""` to fix this error.

struct - fix map custom functions

---

json.go
json_test.go
struct.go

Added handling for custom fake tags in json.RawMessage fields when filling struct fields. This allows for customized generation of json.RawMessage fields without needing to implement the Fakeable interface for a struct.
Closes #360.

Allowing for custom fake tags in json.RawMessage fields in structs

---

xml.go

The intention here should be to initialize a slice with a capacity of  len(xo.Fields) rather than initializing the length of this slice.

fix: fix slice init length
