brianvoe/gofakeit

- data.go
- data_status_code.go
- misc.go
- misc_test.go
- status_code.go
- status_code_test.go
I've made random HTTP status code faker
> Supports random HTTP status code

- generate.go
- misc.go
- misc_test.go
* Expose the abstract types of random data that
can be generated
> feat: add api to query available catagories

- date.go
- date_test.go
I've left the benchmarks regeneration.
Let me know if I should include it here..
> feat: add WeekDay()

- contact_test.go
- data/internet.go
- date_test.go
- internet_test.go
- user_agent_test.go
> add .io domain suffix

- date_test.go
- payment.go
- payment_test.go
- person_test.go
- user_agent_test.go
@brianvoe will fix tests if this looks good to you
> fix: use current year for credit card expiration

- address.go
- address_test.go
I can add test cases and examples if these are acceptable!
Also, I'll refactor out to floatInRange() generic method.
> feat: generate geolocation in a range

- number.go
- number_test.go
@brianvoe 
Thought this would make the library one stop solution for everything.
This work will also be used in the upcoming random struct generation.
I've made good progress on it and expect to send you a PR soon.
>  feat: add random generators for built-in types

- struct.go
- struct_test.go
> Added uint* types for Struct() calls.

- misc.go
- misc_test.go
- string.go
- string_test.go
Added seed to some benchmarks, so they can be compared.
Small refactor and optimization (+10%) of ReplaceWith* functions
Added Digit() function
Fixed RandString panic when input is empty
Optimized ShuffleStrings (20%)
Fixed getRandValue, intDataCheck and dataCheck panic when input is empty
> Small tweaks, tests, fixes and optimizations

- address_test.go
- color_test.go
- contact_test.go
- faker_test.go
- generate_test.go
- internet_test.go
- misc.go
- misc_test.go
- number_test.go
- payment_test.go
- person_test.go
- string_test.go
> fixes digit 9 missing from randDigit

- color.go
- color_test.go
- misc.go
The previous version was generating letter between g and z, which are not valid
> fix: HexColor are now valid

- README.md
- struct.go
- struct_test.go
Add capability to populate array type elements in structs
> generate fake data in struct arrays

- helpers.go
- struct.go
- struct_test.go
A convenient function for shuffling any type of slice.
> feat: shuffle any slice

- internet.go
- internet_test.go
Change IPv4 and IPv6 functions to be able to return the full range of IP addresses available to them
> All Valid IPs

- .gitignore
- beer.go
- beer_test.go
- car.go
- car_test.go
- emoji.go
- emoji_test.go
- faker.go
- food.go
- food_test.go
- time.go
- time_test.go
- Fix NPE with `NewCrypto()` faker instance usage
- Refactor beer, car, emoji, and food files with examples and benchmarks
I did not change the add lookup functions, as I'm unsure of their usage. They still use the package functions.
> Additional feature/rand refactors

- animal.go
- animal_test.go
- app.go
- app_test.go
- color.go
- color_test.go
- file.go
- file_test.go
- game.go
- game_test.go
- image.go
- internet.go
- internet_test.go
- time.go
- time_test.go
- animal
- app
- color
- file
- game
- internet
- time
Again, did not change the add lookup functions.
> More custom rand updates

- README.md
- number.go
- number_test.go
Add hex uint(8,16,..256) strings.
Hello :) 
This pr is a proposal for hex value because i just want to generate random hex value from gofakeit.
That is why I did not implement any additional code such as lookUpFunction, tests.  
If u accept this addition, please leave a comment 😄  thx!
> Support hex string values

- generate.go
- helpers.go
- lookup.go
- struct.go
- struct_test.go
Any reason why the Map object type is not supported on custom functions
> Supporting map properties in struct via custom function

- README.md
I found that i can not use some codes in README to customsized my fakeit function. The reason is package name has not add as prefixion in the previous of struct
> fix not specified package name in README

- string.go
because there was no specific explanation when 0 is passed.
> Docs: add note of function that generate strings with a length of N

- template.go
- template_test.go
Fix the template so user functions are merged with the main function.
Also added a test
> Fix for user template function

- book.go
these descriptions add more context into what's being generated, let me know if it's too long/verbose so we can reach a common format for most of the functions
> add better book lookup descriptions

- game.go
> fix game dice example being a string not a []uint

- minecraft.go
I see you really put in the time in minecraft :smile:
> improve minecraft descs
